title: <p align="center"> Lautaro Cisterna </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lcisterna/">LinkedIn</a> |
  <a href="https://github.com/lautarocisterna">GitHub</a>
  
  <br>   
  I'm an Actuary and currently pursuing a McS in Data Science from University of Arizona.
  Built ML models related for Credit Risk, Marketing, Sports
  and Retail Businesses.
  <br>
  </p>



theme: jekyll-theme-minimal
