title: <p align="center"> Lautaro Cisterna </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lcisterna/">LinkedIn</a> |
  <a href="https://github.com/lautarocisterna">GitHub</a>
  
  <br>   
  I am an Actuary graduated from University of Buenos Aires. Currently I am attending a Master's degree at University of Arizona.
  I have been working as Data Scientist for 3 year now, and I have built different models related to Credit Risk, Marketing, Soccer Analysis, and many other 
  businesses.
  <br>
  </p>



theme: jekyll-theme-minimal
